---
- name:
  user:
    name: "{{moodle_user}}"
    state: present

- name: Install mod PHP
  apt:
      name: libapache2-mod-php7.0
      state: present
      update_cache: yes
      cache_valid_time: 3600

- name: Enable PHP module
  apache2_module:
      name: php7.0
      state: present
  notify:
      - restart apache

- name: Add Moodle from Git
  git:
    repo: "{{moodle_source.git_remote_url}}"
    dest: "{{moodle_source.path}}"
    version: "{{moodle_source.git_version_reference}}"

- name: Add Moodle theme
  git:
    repo: "{{moodle_theme.git_remote_url}}"
    dest: "{{moodle_theme.path}}"
    version: "{{moodle_theme.git_version_reference}}"

- name: Install blocks
  git:
    repo: "{{item.git_remote_url}}"
    dest: "{{item.path}}"
    version: "{{item.git_version_reference}}"
  with_items:
    - "{{moodle_blocks}}"

- name: Set up Moodle database
  mysql_db:
    name: "{{moodle_mysql_db}}"
    state: present
  tags:
    - mysql

- name: Set up Moodle database user
  mysql_user:
    name: "{{moodle_mysql_user}}"
    password: "{{moodle_mysql_password}}"
    priv: '*.*:ALL'
    state: present

- name: Add Moodle config
  template:
    src: "config.php.j2"
    dest: "{{moodle_root}}/config.php"


- name: Add Moodle data directory
  file:
    path: "{{moodle_data_path}}"
    state: directory
    mode: 0755
    owner: "{{moodle_user}}"
    group: "{{moodle_user}}"


- name: Moodle Apache conf
  template:
    src: "http-vhost.conf.j2"
    dest: "{{ apache_conf_path }}/sites-available/{{ moodle_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Enable Moodle apache conf
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ moodle_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ moodle_vhosts_filename }}"
    state: link
  notify: restart apache

- name: Schedule Moodle admin cron
  cron:
    name: "Moodle admin"
    minute: "*/20"
    job: "wget {{moodle_admin_cron}}"

