---
- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure git is installed.
  apt:
    name: "git"
    state: installed

# Required for installing Python-MySQL
- name: Ensure Mysql client installed.
  apt:
    name: "libmysqlclient-dev"
    state: installed

- name: Ensure Python headers installed.
  apt:
    name: "python-dev"
    state: installed

- name: Include all .json and .jsn files in vars/all and all nested directories (2.3)
  include_vars:
    dir: 'vars/local'
    extensions:
        - json
        - yml
        - yaml

- name: Add Lets Encrypt domains dir
  file:
    state: directory
    path: "{{letsencrypt_live}}"
    mode: 0755
    owner: root
  become: yes
